version: '3.8'

services:
  go-app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    container_name: go-app
    env_file:
      - .env.prod
    environment:
      - APP_ENV=production
    ports:
      - '8080:8080'

    networks:
      - monitoring
    expose:
      - '8080'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=30d'
    ports:
      - '9090:9090'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring

    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_LOG_LEVEL=warn # Reduces log verbosity

volumes:
  grafana_data:

networks:
  monitoring:
    driver: bridge
