global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'go-app'
    static_configs:
      - targets:
          - 'go-app-1:8080'
          - 'go-app-2:8080'
          - 'go-app-3:8080'
          - 'go-app-4:8080'
